# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def DescribeClass(self, class_name: str,class_code: str,file_context: str,docstring: typing.Optional[str],method_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.ClassDescription:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DescribeClass(class_name=class_name,class_code=class_code,file_context=file_context,docstring=docstring,method_names=method_names,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DescribeClass", args={
                "class_name": class_name,"class_code": class_code,"file_context": file_context,"docstring": docstring,"method_names": method_names,
            })
            return typing.cast(types.ClassDescription, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DescribeFile(self, file_path: str,file_content: str,class_names: typing.List[str],function_names: typing.List[str],imports: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.FileDescription:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DescribeFile(file_path=file_path,file_content=file_content,class_names=class_names,function_names=function_names,imports=imports,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DescribeFile", args={
                "file_path": file_path,"file_content": file_content,"class_names": class_names,"function_names": function_names,"imports": imports,
            })
            return typing.cast(types.FileDescription, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DescribeFunction(self, function_name: str,function_code: str,file_context: str,docstring: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.FunctionDescription:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DescribeFunction(function_name=function_name,function_code=function_code,file_context=file_context,docstring=docstring,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DescribeFunction", args={
                "function_name": function_name,"function_code": function_code,"file_context": file_context,"docstring": docstring,
            })
            return typing.cast(types.FunctionDescription, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DescribeModule(self, module_name: str,file_summaries: typing.List[str],class_count: int,function_count: int,
        baml_options: BamlCallOptions = {},
    ) -> types.ModuleDescription:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DescribeModule(module_name=module_name,file_summaries=file_summaries,class_count=class_count,function_count=function_count,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DescribeModule", args={
                "module_name": module_name,"file_summaries": file_summaries,"class_count": class_count,"function_count": function_count,
            })
            return typing.cast(types.ModuleDescription, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DescribeClass(self, class_name: str,class_code: str,file_context: str,docstring: typing.Optional[str],method_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClassDescription, types.ClassDescription]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DescribeClass", args={
            "class_name": class_name,"class_code": class_code,"file_context": file_context,"docstring": docstring,"method_names": method_names,
        })
        return baml_py.BamlStream[stream_types.ClassDescription, types.ClassDescription](
          __result__,
          lambda x: typing.cast(stream_types.ClassDescription, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassDescription, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DescribeFile(self, file_path: str,file_content: str,class_names: typing.List[str],function_names: typing.List[str],imports: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.FileDescription, types.FileDescription]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DescribeFile", args={
            "file_path": file_path,"file_content": file_content,"class_names": class_names,"function_names": function_names,"imports": imports,
        })
        return baml_py.BamlStream[stream_types.FileDescription, types.FileDescription](
          __result__,
          lambda x: typing.cast(stream_types.FileDescription, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FileDescription, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DescribeFunction(self, function_name: str,function_code: str,file_context: str,docstring: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.FunctionDescription, types.FunctionDescription]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DescribeFunction", args={
            "function_name": function_name,"function_code": function_code,"file_context": file_context,"docstring": docstring,
        })
        return baml_py.BamlStream[stream_types.FunctionDescription, types.FunctionDescription](
          __result__,
          lambda x: typing.cast(stream_types.FunctionDescription, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FunctionDescription, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DescribeModule(self, module_name: str,file_summaries: typing.List[str],class_count: int,function_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ModuleDescription, types.ModuleDescription]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DescribeModule", args={
            "module_name": module_name,"file_summaries": file_summaries,"class_count": class_count,"function_count": function_count,
        })
        return baml_py.BamlStream[stream_types.ModuleDescription, types.ModuleDescription](
          __result__,
          lambda x: typing.cast(stream_types.ModuleDescription, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ModuleDescription, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def DescribeClass(self, class_name: str,class_code: str,file_context: str,docstring: typing.Optional[str],method_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeClass", args={
            "class_name": class_name,"class_code": class_code,"file_context": file_context,"docstring": docstring,"method_names": method_names,
        }, mode="request")
        return __result__
    async def DescribeFile(self, file_path: str,file_content: str,class_names: typing.List[str],function_names: typing.List[str],imports: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeFile", args={
            "file_path": file_path,"file_content": file_content,"class_names": class_names,"function_names": function_names,"imports": imports,
        }, mode="request")
        return __result__
    async def DescribeFunction(self, function_name: str,function_code: str,file_context: str,docstring: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeFunction", args={
            "function_name": function_name,"function_code": function_code,"file_context": file_context,"docstring": docstring,
        }, mode="request")
        return __result__
    async def DescribeModule(self, module_name: str,file_summaries: typing.List[str],class_count: int,function_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeModule", args={
            "module_name": module_name,"file_summaries": file_summaries,"class_count": class_count,"function_count": function_count,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def DescribeClass(self, class_name: str,class_code: str,file_context: str,docstring: typing.Optional[str],method_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeClass", args={
            "class_name": class_name,"class_code": class_code,"file_context": file_context,"docstring": docstring,"method_names": method_names,
        }, mode="stream")
        return __result__
    async def DescribeFile(self, file_path: str,file_content: str,class_names: typing.List[str],function_names: typing.List[str],imports: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeFile", args={
            "file_path": file_path,"file_content": file_content,"class_names": class_names,"function_names": function_names,"imports": imports,
        }, mode="stream")
        return __result__
    async def DescribeFunction(self, function_name: str,function_code: str,file_context: str,docstring: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeFunction", args={
            "function_name": function_name,"function_code": function_code,"file_context": file_context,"docstring": docstring,
        }, mode="stream")
        return __result__
    async def DescribeModule(self, module_name: str,file_summaries: typing.List[str],class_count: int,function_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeModule", args={
            "module_name": module_name,"file_summaries": file_summaries,"class_count": class_count,"function_count": function_count,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))