# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class ClassDescription(BaseModel):
    purpose: typing.Optional[str] = Field(default=None, description='One sentence: what this class represents and WHEN to use it')
    responsibility: typing.Optional[str] = Field(default=None, description='Single responsibility: what domain concern it owns')
    key_methods: typing.Optional[str] = Field(default=None, description='Most important methods and when to call each')
    state: typing.Optional[str] = Field(default=None, description='Instance data this class manages, or null')
    relationships: typing.Optional[str] = Field(default=None, description='Parent classes, key collaborators, or null')

class FileDescription(BaseModel):
    purpose: typing.Optional[str] = Field(default=None, description='One sentence: what capability this file provides to the codebase')
    contents: typing.Optional[str] = Field(default=None, description='Key exports: classes, functions, constants')
    role: typing.Optional[str] = Field(default=None, description='System context: how other code uses this file')
    dependencies: typing.Optional[str] = Field(default=None, description='Critical imports and why they\'re needed')
    exports: typing.Optional[str] = Field(default=None, description='What to import: primary public API')

class FunctionDescription(BaseModel):
    purpose: typing.Optional[str] = Field(default=None, description='One sentence: what this function does and WHEN to call it')
    behavior: typing.Optional[str] = Field(default=None, description='Key algorithm/steps - what makes this function unique')
    inputs: typing.Optional[str] = Field(default=None, description='Parameters: name, type, constraints')
    outputs: typing.Optional[str] = Field(default=None, description='Return value: type and meaning')
    side_effects: typing.Optional[str] = Field(default=None, description='File I/O, state changes, exceptions thrown, or null')

class ModuleDescription(BaseModel):
    purpose: typing.Optional[str] = Field(default=None, description='One sentence: what this module/package provides')
    components: typing.Optional[str] = Field(default=None, description='Key files and their responsibilities')
    architecture: typing.Optional[str] = Field(default=None, description='How components collaborate')
    public_api: typing.Optional[str] = Field(default=None, description='Recommended imports for external use')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
