# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassDescription": types.ClassDescription,
    "stream_types.ClassDescription": stream_types.ClassDescription,

    "types.FileDescription": types.FileDescription,
    "stream_types.FileDescription": stream_types.FileDescription,

    "types.FunctionDescription": types.FunctionDescription,
    "stream_types.FunctionDescription": stream_types.FunctionDescription,

    "types.ModuleDescription": types.ModuleDescription,
    "stream_types.ModuleDescription": stream_types.ModuleDescription,


}