# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class ClassDescription(BaseModel):
    purpose: str = Field(description='One sentence: what this class represents and WHEN to use it')
    responsibility: str = Field(description='Single responsibility: what domain concern it owns')
    key_methods: str = Field(description='Most important methods and when to call each')
    state: typing.Optional[str] = Field(default=None, description='Instance data this class manages, or null')
    relationships: typing.Optional[str] = Field(default=None, description='Parent classes, key collaborators, or null')

class FileDescription(BaseModel):
    purpose: str = Field(description='One sentence: what capability this file provides to the codebase')
    contents: str = Field(description='Key exports: classes, functions, constants')
    role: str = Field(description='System context: how other code uses this file')
    dependencies: str = Field(description='Critical imports and why they\'re needed')
    exports: str = Field(description='What to import: primary public API')

class FunctionDescription(BaseModel):
    purpose: str = Field(description='One sentence: what this function does and WHEN to call it')
    behavior: str = Field(description='Key algorithm/steps - what makes this function unique')
    inputs: str = Field(description='Parameters: name, type, constraints')
    outputs: str = Field(description='Return value: type and meaning')
    side_effects: typing.Optional[str] = Field(default=None, description='File I/O, state changes, exceptions thrown, or null')

class ModuleDescription(BaseModel):
    purpose: str = Field(description='One sentence: what this module/package provides')
    components: str = Field(description='Key files and their responsibilities')
    architecture: str = Field(description='How components collaborate')
    public_api: str = Field(description='Recommended imports for external use')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
